services:
  - type: web
    name: rag-api

    runtime: python

    plan: free

    buildCommand: |
      pip install uv
      uv sync --frozen
      uv run python scripts/download_model.py

    startCommand: |
      uv run python -m uvicorn app:app --host 0.0.0.0 --port $PORT --log-level debug --workers 2 --timeout-keep-alive 180

    autoDeploy: true
