"""Unit tests for the Chunker stage in the ingestion pipeline.
"""

import os
import sys
import unittest
from pathlib import Path
from unittest.mock import patch

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from errors import ChunkerError, PipelineError
from ingestion.shared_processing.chunker import (
    chunk_document,
    chunk_documents,
    generate_chunk_id,
    pack_chunks_with_overlap,
    split_paragraphs,
    split_sentences,
)
from ingestion.shared_processing.cleaner import clean_document
from models import Chunk, ChunkingConfig, RawDoc, StageCounts


class ChunkerUnitTests(unittest.TestCase):
    # 1. Paragraph splitting
    def test_split_paragraphs(self):
        text = "Paragraph 1 line.\n\nParagraph 2 line.\n\n\nParagraph 3 line."
        paras = split_paragraphs(text)
        self.assertEqual(len(paras), 3)
        self.assertEqual(paras[0], "Paragraph 1 line.")
        self.assertEqual(paras[1], "Paragraph 2 line.")
        self.assertEqual(paras[2], "Paragraph 3 line.")

    def test_split_paragraphs_empty(self):
        self.assertEqual(split_paragraphs(""), [])
        self.assertEqual(split_paragraphs("   \n\n  "), [])

    # 2. Sentence splitting
    def test_split_sentences(self):
        text = "First sentence here. Second sentence follows! Is this the third? Yes, indeed."
        sentences = split_sentences(text)
        self.assertEqual(len(sentences), 4)
        self.assertEqual(sentences[0], "First sentence here.")
        self.assertEqual(sentences[1], "Second sentence follows!")
        self.assertEqual(sentences[2], "Is this the third?")
        self.assertEqual(sentences[3], "Yes, indeed.")

    # 3. Document smaller than chunk_size produces exactly 1 chunk
    def test_short_document_produces_single_chunk(self):
        text = "This is a short paragraph that easily fits within the 512 character budget."
        doc = RawDoc(text=text, source_id="short-doc", metadata={"page_num": 1})
        config = ChunkingConfig(chunk_size=512, chunk_overlap=64)

        chunks = chunk_document(doc, config)
        self.assertEqual(len(chunks), 1)
        self.assertEqual(chunks[0].text, text)
        self.assertEqual(chunks[0].source_id, "short-doc")
        self.assertEqual(chunks[0].page_num, 1)
        self.assertEqual(chunks[0].chunk_id, generate_chunk_id(text))
        self.assertEqual(chunks[0].metadata["chunk_index"], 1)
        self.assertEqual(chunks[0].metadata["total_chunks"], 1)
        self.assertEqual(chunks[0].metadata["char_count"], len(text))

    # 4. Multi-paragraph packing respects budget and paragraph boundaries
    def test_multi_paragraph_packing(self):
        p1 = "Paragraph 1 content."
        p2 = "Paragraph 2 content."
        p3 = "Paragraph 3 content."
        text = f"{p1}\n\n{p2}\n\n{p3}"

        # Budget large enough to hold all 3
        config_large = ChunkingConfig(chunk_size=200, chunk_overlap=20)
        chunks = pack_chunks_with_overlap(text, config_large)
        self.assertEqual(len(chunks), 1)
        self.assertEqual(chunks[0], text)

        # Budget only large enough to hold 1 paragraph at a time
        config_small = ChunkingConfig(chunk_size=30, chunk_overlap=0)
        chunks_small = pack_chunks_with_overlap(text, config_small)
        self.assertEqual(len(chunks_small), 3)
        self.assertEqual(chunks_small[0], p1)
        self.assertEqual(chunks_small[1], p2)
        self.assertEqual(chunks_small[2], p3)

    # 5. Oversized paragraph is split into sentences
    def test_oversized_paragraph_sentence_split(self):
        s1 = "The aerodynamic drag on an aircraft depends on airspeed squared."
        s2 = "Lift is generated by pressure differences across the airfoil surface."
        s3 = "Thrust counteracts drag to maintain steady level flight."
        paragraph = f"{s1} {s2} {s3}"

        # Budget of 100 characters will split into sentences
        config = ChunkingConfig(chunk_size=100, chunk_overlap=0)
        chunks = pack_chunks_with_overlap(paragraph, config)

        self.assertGreater(len(chunks), 1)
        for chunk in chunks:
            self.assertLessEqual(len(chunk), 100)

    # 6. Natural overlap preserves sentence context across chunks
    def test_natural_overlap_preservation(self):
        s1 = "Sentence number one is introductory."
        s2 = "Sentence number two provides essential context."
        s3 = "Sentence number three gives specific details."
        s4 = "Sentence number four concludes the concept."
        text = f"{s1} {s2} {s3} {s4}"

        # chunk_size = 90 (can fit s1 + s2 ≈ 84 chars), chunk_overlap = 50 (can fit s2 ≈ 47 chars)
        config = ChunkingConfig(chunk_size=90, chunk_overlap=50)
        chunks = pack_chunks_with_overlap(text, config)

        self.assertGreater(len(chunks), 1)
        # Verify chunk 1 contains s1 and s2
        self.assertIn(s1, chunks[0])
        self.assertIn(s2, chunks[0])
        # Verify chunk 2 starts with overlapping s2
        self.assertTrue(chunks[1].startswith(s2))

    # 7. Deterministic content-based chunk ID generation (deduplication across sources)
    def test_content_based_chunk_id_identical_across_different_sources(self):
        text_content = "Bernoulli's principle states that an increase in the speed of a fluid occurs simultaneously with a decrease in static pressure."

        # Document 1 from physics.pdf
        doc1 = RawDoc(text=text_content, source_id="physics.pdf", metadata={"page_num": 10})
        # Document 2 with identical content from fluid_dynamics_handbook.docx
        doc2 = RawDoc(text=text_content, source_id="fluid_dynamics_handbook.docx", metadata={"page_num": 1})

        chunks1 = chunk_document(doc1)
        chunks2 = chunk_document(doc2)

        self.assertEqual(len(chunks1), 1)
        self.assertEqual(len(chunks2), 1)
        # Both chunks must have the EXACT SAME content-based chunk_id
        self.assertEqual(chunks1[0].chunk_id, chunks2[0].chunk_id)
        self.assertEqual(chunks1[0].chunk_id, generate_chunk_id(text_content))
        self.assertEqual(chunks1[0].metadata["content_hash"], chunks2[0].metadata["content_hash"])

    # 8. Empty and whitespace-only RawDocs return empty list
    def test_empty_rawdoc_returns_no_chunks(self):
        empty_doc = RawDoc(text="", source_id="empty.pdf")
        ws_doc = RawDoc(text="   \n\n\t  ", source_id="whitespace.pdf")

        self.assertEqual(chunk_document(empty_doc), [])
        self.assertEqual(chunk_document(ws_doc), [])

    # 9. Single gigantic unbroken string is sliced safely
    def test_unbroken_string_fallback(self):
        giant_string = "A" * 600
        doc = RawDoc(text=giant_string, source_id="giant.txt")
        config = ChunkingConfig(chunk_size=200, chunk_overlap=0)

        chunks = chunk_document(doc, config)
        self.assertEqual(len(chunks), 3)
        for chunk in chunks:
            self.assertEqual(len(chunk.text), 200)

    # 10. Config validation
    def test_config_validation(self):
        with self.assertRaises(ValueError):
            pack_chunks_with_overlap("Text", ChunkingConfig(chunk_size=-10, chunk_overlap=0))

        with self.assertRaises(ValueError):
            pack_chunks_with_overlap("Text", ChunkingConfig(chunk_size=100, chunk_overlap=-5))

        with self.assertRaises(ValueError):
            pack_chunks_with_overlap("Text", ChunkingConfig(chunk_size=100, chunk_overlap=100))

    # 11. Environment variable configuration
    def test_chunking_config_from_env(self):
        with patch.dict(os.environ, {"RAG_CHUNK_SIZE": "256", "RAG_CHUNK_OVERLAP": "32"}):
            config = ChunkingConfig.from_env()
            self.assertEqual(config.chunk_size, 256)
            self.assertEqual(config.chunk_overlap, 32)

        # Fallback to alternate env var names
        with patch.dict(os.environ, {"CHUNK_SIZE": "384", "CHUNK_OVERLAP": "48"}, clear=True):
            config = ChunkingConfig.from_env()
            self.assertEqual(config.chunk_size, 384)
            self.assertEqual(config.chunk_overlap, 48)

        # Fallback to config dict
        config_from_dict = ChunkingConfig.from_env({"RAG_CITATION_CHUNK_SIZE": 128, "RAG_CITATION_CHUNK_OVERLAP": 16})
        self.assertEqual(config_from_dict.chunk_size, 128)
        self.assertEqual(config_from_dict.chunk_overlap, 16)

    # 12. Batch document chunking and StageCounts telemetry
    def test_chunk_documents_batch_and_stage_counts(self):
        docs = [
            RawDoc(text="Doc 1 text that fits in one chunk.", source_id="doc1", metadata={"page_num": 1}),
            RawDoc(text="", source_id="doc2", metadata={"page_num": 2}),
            RawDoc(text="Doc 3 paragraph 1.\n\nDoc 3 paragraph 2.", source_id="doc3", metadata={"page_num": 3}),
        ]
        counts = StageCounts()
        config = ChunkingConfig(chunk_size=50, chunk_overlap=0)
        chunks = chunk_documents(docs, config=config, counts=counts)

        self.assertGreater(len(chunks), 0)
        self.assertEqual(counts.chunks_created, len(chunks))

    # 13. Error handling: strict vs non-strict
    def test_error_handling_strict_and_non_strict(self):
        invalid_doc = RawDoc(text=99999, source_id="invalid_type", metadata={"page_num": 5})  # type: ignore

        # strict=True raises ChunkerError (inheriting from PipelineError)
        with self.assertRaises(ChunkerError) as ctx:
            chunk_documents([invalid_doc], strict=True)
        self.assertIsInstance(ctx.exception, PipelineError)
        self.assertEqual(ctx.exception.failure.source, "invalid_type")
        self.assertEqual(ctx.exception.failure.page, 5)

        # strict=False logs and returns empty without throwing
        counts = StageCounts()
        results = chunk_documents([invalid_doc], counts=counts, strict=False)
        self.assertEqual(results, [])

    # 14. End-to-end integration: RawDoc -> clean_document -> chunk_document
    def test_loader_cleaner_chunker_pipeline_integration(self):
        raw_doc = RawDoc(
            text="Mach number is speed of sound ratio.\r\nIt determines compressible flow regime.\r\n\r\nSupersonic regimes exceed Mach 1.0.",
            source_id="fluid-mechanics-1234",
            metadata={
                "file_name": "fluid_mechanics.pdf",
                "source_id": "fluid-mechanics-1234",
                "page_num": 15,
                "page_count": 200,
                "source_format": "pdf",
                "extraction_status": "ok",
                "is_empty": False,
            },
        )

        cleaned_doc = clean_document(raw_doc)
        self.assertIsNotNone(cleaned_doc)

        config = ChunkingConfig(chunk_size=120, chunk_overlap=20)
        chunks = chunk_document(cleaned_doc, config)

        self.assertGreater(len(chunks), 0)
        for chunk in chunks:
            self.assertEqual(chunk.source_id, "fluid-mechanics-1234")
            self.assertEqual(chunk.page_num, 15)
            self.assertEqual(chunk.metadata["file_name"], "fluid_mechanics.pdf")
            self.assertTrue(chunk.chunk_id.startswith("chunk-"))


if __name__ == "__main__":
    unittest.main()
